"""Write the public reference data Autodoss's Reports section reads.

    python scripts/export_autodoss_reference.py ../autodoss/src/lib/reports/reference/publicData.ts

Public data only (Census ACS, BLS LAUS, FRED); nothing from a dealer's file.
Run `refresh-public` first. Re-run when the data is refreshed.
"""
from __future__ import annotations

import json
import sqlite3
import sys
from datetime import date

from trgtmrkt.analysis.catchment import load_centroids
from trgtmrkt.sources import gazetteer

COUNTY_NAMES = {
    "47003": "Bedford", "47015": "Cannon", "47037": "Davidson", "47119": "Maury",
    "47149": "Rutherford", "47165": "Sumner", "47187": "Williamson", "47189": "Wilson",
}


def num(value, places=4):
    return None if value is None or value != value else round(float(value), places)


def main(out_path: str) -> None:
    conn = sqlite3.connect("data/trgtmrkt.db")
    conn.row_factory = sqlite3.Row
    centroids = load_centroids(str(gazetteer.DEFAULT_PATH))
    zips = []
    for r in conn.execute("SELECT * FROM acs_zcta ORDER BY zip5"):
        lat_lon = centroids.get(r["zip5"])
        if lat_lon is None:
            continue
        zips.append({
            "zip": r["zip5"], "lat": round(lat_lon[0], 5), "lon": round(lat_lon[1], 5),
            "population": num(r["population"], 0), "households": num(r["households"], 0),
            "householdsUnder50k": num(r["hh_under_50k"], 0), "medianIncome": num(r["median_hh_income"], 0),
            "renterShare": num(r["renter_share"]), "noVehicleShare": num(r["no_vehicle_share"]),
            "povertyRate": num(r["poverty_rate"]), "unemploymentRate": num(r["unemployment_rate"]),
        })
    acs_year = conn.execute("SELECT MAX(acs_year) FROM acs_zcta").fetchone()[0]

    counties = []
    for fips, name in COUNTY_NAMES.items():
        rows = conn.execute("SELECT month, rate FROM county_unemployment WHERE fips=? ORDER BY month", (fips,)).fetchall()
        if rows:
            counties.append({"fips": fips, "name": name,
                             "months": [{"month": m, "rate": rate} for m, rate in rows[-13:]]})

    macro = []
    for m in conn.execute("SELECT series, title FROM macro_series_meta WHERE copyrighted = 0 ORDER BY series"):
        pts = conn.execute("SELECT date, value FROM macro_series WHERE series=? ORDER BY date", (m["series"],)).fetchall()
        macro.append({"series": m["series"], "title": m["title"],
                      "points": [{"date": d, "value": v} for d, v in pts[-60:]]})

    data = {"generated": date.today().isoformat(), "acsYear": acs_year, "zips": zips,
            "counties": counties, "macro": macro}
    body = json.dumps(data, indent=1)
    with open(out_path, "w") as fh:
        fh.write(
            "/* Public reference data for the Reports section. GENERATED by trgtmrkt's\n"
            "   scripts/export_autodoss_reference.py -- do not edit by hand.\n\n"
            "   Sources: U.S. Census Bureau ACS 5-year (by ZIP code tabulation area), BLS Local Area\n"
            "   Unemployment Statistics (by county), and FRED. Nothing here comes from a dealer's file.\n"
            "   Showing FRED data requires the notice in fredNotice; see FRED_SERIES. */\n\n"
            "import type { PublicData } from '../publicTypes';\n\n"
            f"export const PUBLIC_DATA: PublicData = {body};\n"
        )
    print(f"{len(zips)} ZIPs, {len(counties)} counties, {len(macro)} macro series -> {out_path}")


if __name__ == "__main__":
    main(sys.argv[1])
